teletask:
  host: "localhost"
  port: 1234
  id: "MAN_${teletask.host}_${teletask.port}"
  configFile: "/teletask2mqtt/config.json"
  version: "@gateway.version@"
  mqtt:
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    retained: "false"
    clientId: "teletask2mqtt"
    prefix: "teletask2mqtt"
    discovery_prefix: "homeassistant"

spring:
  main:
    banner-mode: off
  application:
    name: teletask2mqtt

logging:
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} -%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
  level:
    io.github.ridiekel.jeletask: INFO
    io.github.ridiekel.jeletask.mqtt: INFO
